"""Run a local-only walkthrough of the cached transcript pipeline.

This is deliberately *not* an end-to-end RAG answer.  It uses a clearly marked
synthetic fixture and the project's real cache -> chunking -> knowledge-base
adapter path, while replacing external services with in-memory test doubles.
No video, audio, transcript, embedding, or model result is fetched or claimed.
"""

from __future__ import annotations

import json
import sys
import tempfile
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from yt_agent.config import Settings
from yt_agent.pipeline import IngestPipeline
from yt_agent.youtube import VideoRef


FIXTURE_VIDEO = VideoRef(
    video_id="offline-fixture",
    title="Synthetic offline fixture — not a YouTube video",
    channel="Local test data",
    webpage_url="https://example.invalid/youtube-rag-offline-fixture",
    duration=24,
)

FIXTURE_TRANSCRIPT = {
    "video": {
        "video_id": FIXTURE_VIDEO.video_id,
        "title": FIXTURE_VIDEO.title,
        "channel": FIXTURE_VIDEO.channel,
        "webpage_url": FIXTURE_VIDEO.webpage_url,
        "duration": FIXTURE_VIDEO.duration,
    },
    "language": "es",
    "segments": [
        {
            "start": 0.0,
            "end": 8.0,
            "text": "Este fixture sintetico ejercita la ruta local de cache.",
        },
        {
            "start": 9.0,
            "end": 18.0,
            "text": "El pipeline genera chunks con metadatos y una fuente con marca de tiempo.",
        },
        {
            "start": 19.0,
            "end": 24.0,
            "text": "No descarga video ni invoca Whisper durante esta demostracion.",
        },
    ],
}


class RecordingKnowledgeBase:
    """In-memory adapter used only to show what the pipeline would index."""

    def __init__(self) -> None:
        self.chunks = []

    def upsert_chunks(self, chunks) -> None:
        self.chunks.extend(chunks)


class FixtureYoutube:
    def resolve_videos(self, _url: str, max_videos: int | None = None) -> list[VideoRef]:
        return [FIXTURE_VIDEO]

    def download_audio(self, _video: VideoRef):  # pragma: no cover - safety rail
        raise AssertionError("The cached fixture must not download audio.")


class NoNetworkWhisper:
    def transcribe(self, *_args, **_kwargs):  # pragma: no cover - safety rail
        raise AssertionError("The cached fixture must not call Whisper.")


def _settings(data_dir: Path) -> Settings:
    return Settings(
        data_dir=data_dir,
        whisper_url="http://not-used.local",
        chroma_host="not-used.local",
        chroma_port=0,
        chroma_collection="offline_fixture",
        ollama_base_url="http://not-used.local",
        ollama_model="not-used",
        embedding_provider="not-used",
        embedding_model="not-used",
        ollama_embed_model="not-used",
        retrieve_k=3,
        chunk_max_seconds=120,
        chunk_overlap_seconds=0,
        chunk_max_chars=2600,
    )


def render_demo() -> str:
    """Return stable, human-readable output from the real cached pipeline path."""
    with tempfile.TemporaryDirectory(prefix="yt-rag-offline-fixture-") as temp_dir:
        settings = _settings(Path(temp_dir))
        settings.ensure_dirs()
        transcript_path = settings.transcripts_dir / f"{FIXTURE_VIDEO.video_id}.json"
        transcript_path.write_text(
            json.dumps(FIXTURE_TRANSCRIPT, ensure_ascii=False), encoding="utf-8"
        )

        knowledge_base = RecordingKnowledgeBase()
        pipeline = IngestPipeline(
            settings=settings,
            knowledge_base=knowledge_base,
            whisper=NoNetworkWhisper(),
            youtube=FixtureYoutube(),
        )
        results = pipeline.ingest("fixture://offline", on_progress=lambda _message: None)

    result = results[0]
    lines = [
        "Offline fixture demo — reproducible and local-only",
        "Fixture: synthetic test data; not a YouTube video or real transcript.",
        "External services used: none (no YouTube, Whisper, Chroma, embeddings, or Ollama).",
        f"Cached pipeline result: {result.status}; chunks passed to the adapter: {result.chunks}.",
        "Timestamped source metadata generated by yt_agent.chunking.build_chunks:",
    ]
    for index, chunk in enumerate(knowledge_base.chunks, start=1):
        lines.append(
            f"[{index}] {chunk.metadata['start_time']}-{chunk.metadata['end_time']} "
            f"{chunk.metadata['timestamp_url']}"
        )
    return "\n".join(lines)


if __name__ == "__main__":
    print(render_demo())
